# group_vars/all.yml
proxmox_api_url: https://{{ hostvars['proxmox'].ansible_host }}:8006/api2/json
proxmox_user: root@pam
proxmox_password: 159kop        # or reference an Ansible Vault variable
proxmox_node: homelab
vm_name: android-dev
vm_id: 110
vm_memory: 8192
vm_cores: 4
vm_disk_size: 20G
vm_bridge: vmbr0
vm_ssh_key: "{{ lookup('file', '~/.ssh/id_ed25519_ansible.pub') }}"

